### ISSUE TITLE
[BUG] Claude Code 2.1.114 broken on macOS 11 (Big Sur) — native binary requires macOS 13.0+

### ISSUE THREAD

**Issue by Ouroboros505** [anthropics/claude-code#50445]
### Preflight Checklist

- [x] I have searched [existing issues](https://github.com/anthropics/claude-code/issues?q=is%3Aissue%20state%3Aopen%20label%3Abug) and this hasn't been reported yet
- [x] This is a single bug report (please file separate reports for different bugs)
- [x] I am using the latest version of Claude Code

### What's Wrong?

 After updating from 2.1.98 to 2.1.114, Claude Code crashes immediately on launch:
                                                                                                   
 dyld: Symbol not found: _ubrk_clone
  Referenced from: /Users/.../.nvm/versions/node/v22.15.0/bin/claude (which was built for Mac  OS X 13.0)                                                                                       
 Expected in: /usr/lib/libicucore.A.dylib
 zsh: abort      claude

The native binary (claude.exe) has minos 13.0 set, which is incompatible with macOS 11. The cli-wrapper.cjs also calls the native binary, so there's no pure-JS fallback.

System info:
 - macOS 11.7.10 (Big Sur)
 - iMac15,1 (Late 2014)
 - Node v22.15.0 via nvm                                                                        

What I've tried:                                                                               
  - Node 18, 20, and 22 — same crash on all
  - npm install -g @anthropic-ai/claude-code@latest — same binary, same crash                    
  - node cli-wrapper.cjs — also calls native binary, same crash  

This is a breaking change with no warning. Users on macOS 11 who update cannot start new sessions. The documented requirement was macOS 10.15+ until recently. There is no way to run the latest version on macOS 11.

### What Should Happen?

Claude Code should either launch successfully on macOS 11 as it did with version 2.1.98, or the installer should detect the OS version and warn the user before updating to an incompatible version. Ideally, a macOS 11-compatible binary or a pure-JS/Node fallback should be available for older systems.

### Error Messages/Logs

```shell

```

### Steps to Reproduce

1. Have a Mac running macOS 11 (Big Sur) — e.g., iMac15,1 with macOS 11.7.10                   
2. Install Node via nvm (any version — 18, 20, or 22 all reproduce the issue)                
3. Have Claude Code 2.1.98 installed and working via npm install -g                            
  @anthropic-ai/claude-code@2.1.98                                                                 
 4. Update to latest: npm install -g @anthropic-ai/claude-code@latest (installs 2.1.114)        
 5. Run claude or claude --version                                                              
 6. Crash:     
  dyld: Symbol not found: _ubrk_clone                                                            
   Referenced from: /Users/.../.nvm/versions/node/v22.15.0/bin/claude (which was built for Mac  
  OS X 13.0)
     Expected in: /usr/lib/libicucore.A.dylib                                                     
   zsh: abort      claude                                                                         
 7. Attempting node cli-wrapper.cjs also crashes with the same error since it calls the same native binary. 

### Claude Model

Opus

### Is this a regression?

Yes, this worked in a previous version

### Last Working Version

2.1.98

### Claude Code Version

Cannot run claude --version — it crashes before producing output. Installed version per           package.json is 2.1.114. Previous working version was 2.1.98.

### Platform

Other

### Operating System

macOS

### Terminal/Shell

Terminal.app (macOS)
