### ISSUE TITLE
[BUG] Desktop Connector Install/Uninstall button is disabled after upgrading Claude Desktop to v1.21459

### ISSUE THREAD

**Issue by terry623** [anthropics/claude-code#77677]
### Preflight Checklist

- [x] I have searched [existing issues](https://github.com/anthropics/claude-code/issues?q=is%3Aissue%20state%3Aopen%20label%3Abug) and this hasn't been reported yet
- [x] This is a single bug report (please file separate reports for different bugs)
- [x] I am using the latest version of Claude Code

### What's Wrong?

After upgrading Claude Desktop from v1.20186 to v1.21459, the Install/Uninstall button for Desktop Connectors is disabled (greyed out) in the Connectors list.

This issue has been reproduced on both macOS and Windows across multiple machines.

Because the button is disabled, users can no longer install or remove custom Desktop Connectors.

This appears to be a regression, as the same workflow works correctly on v1.20186.

### What Should Happen?

The Install/Uninstall button should remain enabled in the Connectors list after upgrading Claude Desktop so users can continue installing and removing Desktop Connectors.

### Error Messages/Logs

```

This is the error in developer panel:

Uncaught (in promise) Error: Error invoking remote method
'$eipc_message$_7e1d0999-1d7f-4b41-a6c4-
a0f6f7b779d2_$_claude.settings_$_Extensions_$_getInstalledExtensionsWithState':
TypeError: u._parse is not a function

```

### Steps to Reproduce

1. Install Claude Desktop v1.20186.
2. Open the Connectors list.
3. Verify that the Install/Uninstall button for Desktop Connectors is enabled.
4. Upgrade Claude Desktop to v1.21459.
5. Open the Connectors list again.
6. Observe that the Install/Uninstall button is disabled (greyed out).

### Claude Model

None

### Is this a regression?

Yes, this worked in a previous version

### Last Working Version

Claude Desktop（v1.20186）

### Claude Code Version

Claude Desktop（v1.21459）

### Platform

Anthropic API

### Operating System

macOS

### Terminal/Shell

Other
