### ISSUE TITLE
[BUG] Problems updating 1.0.58 -> 1.0.59

### ISSUE THREAD

**Issue by florath** [anthropics/claude-code#4280]
## Environment
- Platform (select one): Sorry - no idea what to mark here
  - [ ] Anthropic API
  - [ ] AWS Bedrock
  - [ ] Google Vertex AI
  - [ ] Other: 
- Claude CLI version: 1.0.58 -> 1.0.59
- Operating System: Debian 12 (6.1.140-1)
- Terminal: GNOME Terminal 3.46.8

## Bug Description
Update from 1.0.58 to 1.59 failed. Manual interaction was needed to get it running again.

## Steps to Reproduce
1. Step

```
$ claude update
Current version: 1.0.58
Checking for updates...
New version available: 1.0.59 (current: 1.0.58)
Installing update...
Warning: Could not determine installation type
Attempting global update based on file detection...
Using global installation update method...
Error: Failed to install update
Or consider migrating to a local installation with:
  claude migrate-installer

```

2. Claude was removed:
```
$ claude
-bash: /home/florath/npm-global/bin/claude: No such file or directory

```

3. Also manual installation failed:
```
$ npm install -g @anthropic-ai/claude-code
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /home/florath/npm-global/lib/node_modules/@anthropic-ai/claude-code
npm ERR! dest /home/florath/npm-global/lib/node_modules/@anthropic-ai/.claude-code-n1GHRQW4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/home/florath/npm-global/lib/node_modules/@anthropic-ai/claude-code' -> '/home/florath/npm-global/lib/node_modules/@anthropic-ai/.claude-code-n1GHRQW4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/florath/.npm/_logs/2025-07-24T06_25_28_905Z-debug-0.log

```

4. Claude failed to start:
```
$ claude 
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[CompileError: WebAssembly.instantiate(): expected 83072 bytes, fell off end @+1233]

Node.js v18.19.0

```

## Expected Behavior
Seamless update.

## Actual Behavior
Failed update with unusable installation.

## Additional Context
As a workaround (for all those who are also running in this problem), I had to remove the above mentioned directories.

 ```
rm -fr /home/florath/npm-global/lib/node_modules/@anthropic-ai/claude-code 
rm -fr /home/florath/npm-global/lib/node_modules/@anthropic-ai/.claude-code-n1GHRQW4/ 
```

which then gave me a working claude code version:

```
$ npm install -g @anthropic-ai/claude-code

$ claude --version
1.0.59 (Claude Code)

```

**Comment by florath** [comment]
Mostly the same happens again when updating to 1.0.60:

In a claude session:

`✗ Auto-update failed · Try claude doctor or npm i -g @anthropic-ai/claude-code
`
But:

```
$ claude 
-bash: /home/florath/npm-global/bin/claude: No such file or directory

$ npm install -g @anthropic-ai/claude-code
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /home/florath/npm-global/lib/node_modules/@anthropic-ai/claude-code
npm ERR! dest /home/florath/npm-global/lib/node_modules/@anthropic-ai/.claude-code-n1GHRQW4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/home/florath/npm-global/lib/node_modules/@anthropic-ai/claude-code' -> '/home/florath/npm-global/lib/node_modules/@anthropic-ai/.claude-code-n1GHRQW4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/florath/.npm/_logs/2025-07-25T06_19_07_084Z-debug-0.log
```

The same workaround (e.g. completely removing and re-installation) works also here.

**Comment by weisisheng** [comment]
Dang, fix doesn't work for me, still receiving the error I woke up to " Error: Cannot find module './yoga.wasm' "

Tried, 1.0.58-60

ubuntu 24.04, node 21.x

**Comment by florath** [comment]
FYI: the update from 1.0.60 to 1.0.61 worked for me without any problem.

```
$ claude update
Current version: 1.0.60
Checking for updates...
New version available: 1.0.61 (current: 1.0.60)
Installing update...
Warning: Could not determine installation type
Attempting global update based on file detection...
Using global installation update method...
Successfully updated from 1.0.60 to version 1.0.61

$ claude --version
1.0.61 (Claude Code)
```

**Comment by botera5571** [comment]
Still cannot update.

**Comment by florath** [comment]
While the update worked for all versions in between, I run now in the same problem updating to 1.0.68.
(The same workaround is still working for me.)

**Comment by benj01** [comment]
I had the issue that i could not update (would say it did but then would not, so it appeared) and doctor would freeze. The issue was I had duplicate claude code installation. Deleted the ones in C:\nvm4w\nodejs, afterwards all was well

**Comment by Amirsadjad** [comment]
I had this issue for lots of updates on claude code. the issue I found was when npm tries to install a new version it renames the old one to something like .claude-code-n1GHRQW4 (as someone mentioned here) and it's not like it's a random name. if I try to updated it again it would go in the same exactly named directory. so when I have a failed update and the package is partially downloaded after that the update will fail duo to npm not being able to rename the old directory to this temp one. 

How to fix it?

```
ls {YOUR_PATH}/node_modules/@anthropic-ai/
rm -rf {YOUR_PATH}/@anthropic-ai/.claude-code-*
npm install -g @anthropic-ai/claude-code
```
